trigger:
- main

pool:
  vmImage: ubuntu-latest
variables:
  resourceGroupName: "azlcm1"
  location: "westeurope"
  workloadName: "azlcm25"
  workloadEnv: "dev" 
  registryURI: $(workloadName)azcontreg$(workloadEnv).azurecr.io 
  imageName: "azure-lcm-poc"

stages:
  - stage: CreateInfrastructure
    displayName: 'Create Infrastructure'
    jobs:
    - job: CreateInfra
      displayName: 'Create infrastructure'
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Deploy infrastructure'
        inputs:
          azureSubscription: 'masterconnection'
          scriptType: bash
          scriptPath: 'infra/build-infra.sh'
          workingDirectory: infra
        env:
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          workloadName: $(workloadName)
          workloadEnv: $(workloadEnv)

  - stage: BuildContainerImage
    displayName: 'Build Container image'
    jobs:
    - job: BuildContainer
      displayName: 'Build Container image'
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Build-Container-Image'
        inputs:
          azureSubscription: 'masterconnection'
          scriptType: bash
          scriptPath: 'infra/build-container.sh'
        env:
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          workloadName: $(workloadName)
          workloadEnv: $(workloadEnv)
          registryURI: $(registryURI)
          imageName: $(imageName)
          imageTag: $(Build.BuildId)

  - stage: ExecuteJob
    displayName: 'Execute container'
    jobs:
    - job: ExecuteJob
      displayName: 'Execute container'
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Run-Job'
        inputs:
          azureSubscription: 'masterconnection'
          scriptType: bash
          scriptPath: 'infra/execute-job.sh'
        env:
          resourceGroupName: $(resourceGroupName)
          location: $(location)
          workloadName: $(workloadName)
          workloadEnv: $(workloadEnv)
          registryURI: $(registryURI)
          imageName: $(imageName)
          imageTag: $(Build.BuildId)
          GTIHUB_PAT: $(GTIHUB_PAT)
          STORAGE_ACCOUNT: $(workloadName)storageacc$(workloadEnv)
          AZURE_DEVOPS_ORGNAME: damayantibhuyan
          AZURE_DEVOPS_PAT: $(AZURE_DEVOPS_PAT)
          AZURE_OPENAI_ENDPOINT: https://azopenai-lcm.openai.azure.com/
          AZURE_OPENAI_API_KEY: $(AZURE_OPENAI_API_KEY)      
